name: Pull Request

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "LISCENSE"
      - ".gitignore"
      - "docs/**/*"
      - examples/**/*"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          path: | 
            ~/.npm
            ./node_modules

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Run unit test
        run: npm run test

      # - name: Run e2e test
      #   uses: cypress-io/github-action@v6
      #   with:
      #     browser: chrome
